In [2]:
import pandas as pd
import numpy as np

data = pd.read_csv("../Medical_appointment_data.csv")

In [4]:
def clean_text(x):
    if pd.isna(x):
        return x
    return str(x).strip().lower()

cols = ['specialty','appointment_time','no_show','disability','place','appointment_shift']

for col in cols:
    data[col] = data[col].apply(clean_text)

In [5]:
data['age'] = data['age'].fillna(data['age'].median())

cat_cols = ['specialty','disability','place','appointment_shift']
for col in cat_cols:
    data[col] = data[col].fillna('unknown')

In [6]:
data.head()

,specialty,appointment_time,gender,no_show,disability,place,appointment_shift,age,under_12_years_old,over_60_years_old,...,storm_day_before,rain_intensity,heat_intensity,appointment_date_continuous,Hipertension,Diabetes,Alcoholism,Handcap,Scholarship,SMS_received
0,psychotherapy,17,F,yes,intellectual,lake marvinville,afternoon,9.0,1,0,...,1,no_rain,warm,2020-01-01,0,0,0,0,0,0
1,unknown,7,M,no,intellectual,itapema,morning,11.0,1,0,...,1,no_rain,cold,2020-01-01,0,0,0,0,0,0
2,speech therapy,16,M,no,intellectual,itajaí,afternoon,8.0,1,0,...,1,no_rain,warm,2020-01-01,0,0,0,0,0,0
3,speech therapy,14,M,yes,intellectual,sarahside,afternoon,9.0,1,0,...,1,moderate,mild,2020-01-01,0,0,0,0,0,1
4,physiotherapy,8,M,no,motor,itajaí,morning,12.0,0,0,...,1,no_rain,mild,2020-01-01,0,0,0,0,0,0

In [12]:
data['no_show'] = data['no_show'].map({'yes':1,'no':0})
data = data.dropna(subset=['no_show'])

In [13]:
data

,specialty,appointment_time,gender,no_show,disability,place,appointment_shift,age,under_12_years_old,over_60_years_old,...,storm_day_before,rain_intensity,heat_intensity,appointment_date_continuous,Hipertension,Diabetes,Alcoholism,Handcap,Scholarship,SMS_received
0,psychotherapy,17,F,1,intellectual,lake marvinville,afternoon,9.0,1,0,...,1,no_rain,warm,2020-01-01,0,0,0,0,0,0
1,unknown,7,M,0,intellectual,itapema,morning,11.0,1,0,...,1,no_rain,cold,2020-01-01,0,0,0,0,0,0
2,speech therapy,16,M,0,intellectual,itajaí,afternoon,8.0,1,0,...,1,no_rain,warm,2020-01-01,0,0,0,0,0,0
3,speech therapy,14,M,1,intellectual,sarahside,afternoon,9.0,1,0,...,1,moderate,mild,2020-01-01,0,0,0,0,0,1
4,physiotherapy,8,M,0,motor,itajaí,morning,12.0,0,0,...,1,no_rain,mild,2020-01-01,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109588,psychotherapy,16,M,1,intellectual,unknown,afternoon,18.0,0,0,...,1,no_rain,mild,2021-05-11,0,0,0,0,0,0
109589,speech therapy,9,F,1,motor,port georgestad,morning,18.0,0,0,...,1,moderate,warm,2021-05-11,0,0,0,0,0,0
109590,psychotherapy,13,F,0,intellectual,erinton,afternoon,8.0,1,0,...,1,moderate,mild,2021-05-11,0,0,0,0,0,1
109591,physiotherapy,8,F,0,motor,camboriu,morning,7.0,1,0,...,1,no_rain,warm,2021-05-11,0,0,0,0,0,0
109592,psychotherapy,11,M,0,unknown,unknown,morning,12.0,0,0,...,1,weak,cold,2021-05-12,0,0,0,0,0,0

In [14]:
data['appointment_date_continuous'] = pd.to_datetime(data['appointment_date_continuous'])
data['day'] = data['appointment_date_continuous'].dt.day
data['month'] = data['appointment_date_continuous'].dt.month
data['weekday'] = data['appointment_date_continuous'].dt.weekday

data['age'] = data['age'].astype(int)
data.drop('appointment_date_continuous', axis=1, inplace=True)
data

,specialty,appointment_time,gender,no_show,disability,place,appointment_shift,age,under_12_years_old,over_60_years_old,...,heat_intensity,Hipertension,Diabetes,Alcoholism,Handcap,Scholarship,SMS_received,day,month,weekday
0,psychotherapy,17,F,1,intellectual,lake marvinville,afternoon,9,1,0,...,warm,0,0,0,0,0,0,1,1,2
1,unknown,7,M,0,intellectual,itapema,morning,11,1,0,...,cold,0,0,0,0,0,0,1,1,2
2,speech therapy,16,M,0,intellectual,itajaí,afternoon,8,1,0,...,warm,0,0,0,0,0,0,1,1,2
3,speech therapy,14,M,1,intellectual,sarahside,afternoon,9,1,0,...,mild,0,0,0,0,0,1,1,1,2
4,physiotherapy,8,M,0,motor,itajaí,morning,12,0,0,...,mild,0,0,0,0,0,0,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109588,psychotherapy,16,M,1,intellectual,unknown,afternoon,18,0,0,...,mild,0,0,0,0,0,0,11,5,1
109589,speech therapy,9,F,1,motor,port georgestad,morning,18,0,0,...,warm,0,0,0,0,0,0,11,5,1
109590,psychotherapy,13,F,0,intellectual,erinton,afternoon,8,1,0,...,mild,0,0,0,0,0,1,11,5,1
109591,physiotherapy,8,F,0,motor,camboriu,morning,7,1,0,...,warm,0,0,0,0,0,0,11,5,1
109592,psychotherapy,11,M,0,unknown,unknown,morning,12,0,0,...,cold,0,0,0,0,0,0,12,5,2

In [15]:
data = data.ffill()
data = data.bfill()
data

,specialty,appointment_time,gender,no_show,disability,place,appointment_shift,age,under_12_years_old,over_60_years_old,...,heat_intensity,Hipertension,Diabetes,Alcoholism,Handcap,Scholarship,SMS_received,day,month,weekday
0,psychotherapy,17,F,1,intellectual,lake marvinville,afternoon,9,1,0,...,warm,0,0,0,0,0,0,1,1,2
1,unknown,7,M,0,intellectual,itapema,morning,11,1,0,...,cold,0,0,0,0,0,0,1,1,2
2,speech therapy,16,M,0,intellectual,itajaí,afternoon,8,1,0,...,warm,0,0,0,0,0,0,1,1,2
3,speech therapy,14,M,1,intellectual,sarahside,afternoon,9,1,0,...,mild,0,0,0,0,0,1,1,1,2
4,physiotherapy,8,M,0,motor,itajaí,morning,12,0,0,...,mild,0,0,0,0,0,0,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109588,psychotherapy,16,M,1,intellectual,unknown,afternoon,18,0,0,...,mild,0,0,0,0,0,0,11,5,1
109589,speech therapy,9,F,1,motor,port georgestad,morning,18,0,0,...,warm,0,0,0,0,0,0,11,5,1
109590,psychotherapy,13,F,0,intellectual,erinton,afternoon,8,1,0,...,mild,0,0,0,0,0,1,11,5,1
109591,physiotherapy,8,F,0,motor,camboriu,morning,7,1,0,...,warm,0,0,0,0,0,0,11,5,1
109592,psychotherapy,11,M,0,unknown,unknown,morning,12,0,0,...,cold,0,0,0,0,0,0,12,5,2

In [16]:
data = pd.get_dummies(data, drop_first=True)
data

,no_show,age,under_12_years_old,over_60_years_old,patient_needs_companion,average_temp_day,average_rain_day,max_temp_day,max_rain_day,rainy_day_before,...,place_zunigatown,place_zunigaview,appointment_shift_morning,rain_intensity_moderate,rain_intensity_no_rain,rain_intensity_weak,heat_intensity_heavy_cold,heat_intensity_heavy_warm,heat_intensity_mild,heat_intensity_warm
0,1,9,1,0,1,23.18,0.00,27.5,0.0,1,...,False,False,False,False,True,False,False,False,False,True
1,0,11,1,0,1,14.31,0.02,16.5,0.6,1,...,False,False,True,False,True,False,False,False,False,False
2,0,8,1,0,1,21.61,0.01,29.9,0.2,1,...,False,False,False,False,True,False,False,False,False,True
3,1,9,1,0,1,21.39,0.11,24.1,1.4,1,...,False,False,False,True,False,False,False,False,True,False
4,0,12,0,0,0,20.15,0.02,23.1,0.2,1,...,False,False,True,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109588,1,18,0,0,0,18.97,0.00,25.6,0.8,1,...,False,False,False,False,True,False,False,False,True,False
109589,1,18,0,0,0,24.46,0.23,31.4,8.7,1,...,False,False,True,True,False,False,False,False,False,True
109590,0,8,1,0,1,20.88,0.00,23.8,5.1,1,...,False,False,False,True,False,False,False,False,True,False
109591,0,7,1,0,1,24.89,0.00,28.8,0.0,1,...,False,False,True,False,True,False,False,False,False,True
109592,0,12,0,0,0,18.85,0.16,20.8,2.0,1,...,False,False,True,False,False,True,False,False,False,False

In [ ]:
data.to_csv("../clean_data.csv", index=False)

In [ ]:
clean = pd.read_csv("../clean_data.csv")

,no_show,age,under_12_years_old,over_60_years_old,patient_needs_companion,average_temp_day,average_rain_day,max_temp_day,max_rain_day,rainy_day_before,...,place_zunigatown,place_zunigaview,appointment_shift_morning,rain_intensity_moderate,rain_intensity_no_rain,rain_intensity_weak,heat_intensity_heavy_cold,heat_intensity_heavy_warm,heat_intensity_mild,heat_intensity_warm
0,1,9,1,0,1,23.18,0.00,27.5,0.0,1,...,False,False,False,False,True,False,False,False,False,True
1,0,11,1,0,1,14.31,0.02,16.5,0.6,1,...,False,False,True,False,True,False,False,False,False,False
2,0,8,1,0,1,21.61,0.01,29.9,0.2,1,...,False,False,False,False,True,False,False,False,False,True
3,1,9,1,0,1,21.39,0.11,24.1,1.4,1,...,False,False,False,True,False,False,False,False,True,False
4,0,12,0,0,0,20.15,0.02,23.1,0.2,1,...,False,False,True,False,True,False,False,False,True,False

In [12]:
print(data.isnull().sum())

specialty                         0
appointment_time                  0
gender                            0
no_show                           0
disability                        0
place                             0
appointment_shift                 0
age                               0
under_12_years_old                0
over_60_years_old                 0
patient_needs_companion           0
average_temp_day               2211
average_rain_day               2245
max_temp_day                   2227
max_rain_day                   2263
rainy_day_before                  0
storm_day_before                  0
rain_intensity                    0
heat_intensity                    0
appointment_date_continuous       0
Hipertension                      0
Diabetes                          0
Alcoholism                        0
Handcap                           0
Scholarship                       0
SMS_received                      0
dtype: int64